version: "3"
services: 
  web:
    build: .
    image: node-server:1.0
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./spider:/root/app
    networks:
      - net01
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - net01
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: "news"
networks:
  net01:

volumes:
  mysqldata:
